name: e2e.trigger

on:
  pull_request:
    types: [labeled]

jobs:
  pr-description:
    if: ${{ contains(github.event.label.name, 'Trigger record test') }}

    runs-on: [self-hosted, custom-runner, small-runner]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Run record
      id: run-record-test
      run: |
        echo "SUCCESS"
